"""live readings from the CPCB real-time feed

Revision ID: 0001
Revises: 
Create Date: 2026-09-12 20:54:45.002189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_stations')),
    sa.UniqueConstraint('name', name=op.f('uq_live_stations_name'))
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('stations_seen', sa.Integer(), nullable=False),
    sa.Column('readings_inserted', sa.Integer(), nullable=False),
    sa.Column('readings_purged', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name=op.f('ck_scrape_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_table('live_readings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('pollutant', sa.String(length=8), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("pollutant IN ('PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3', 'NH3')", name=op.f('ck_live_readings_pollutant')),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_live_readings_scrape_run_id_scrape_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['live_stations.id'], name=op.f('fk_live_readings_station_id_live_stations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_readings')),
    sa.UniqueConstraint('station_id', 'pollutant', 'observed_at', name=op.f('uq_live_readings_station_id'))
    )
    with op.batch_alter_table('live_readings', schema=None) as batch_op:
        batch_op.create_index('ix_live_readings_observed_at', ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_live_readings_observed_at')

    op.drop_table('live_readings')
    op.drop_table('scrape_runs')
    op.drop_table('live_stations')
    # ### end Alembic commands ###
