"""historical city and station data

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-13 03:49:25.166039
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("name", "state", name=op.f("uq_cities_name")),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
    )
    op.create_table(
        "periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=20), nullable=False),
        sa.Column("frequency", sa.String(length=5), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.CheckConstraint("frequency IN ('FY', 'CY', 'MONTH')", name=op.f("ck_periods_frequency")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_periods")),
        sa.UniqueConstraint("key", name=op.f("uq_periods_key")),
    )
    op.create_table(
        "city_aqi_days",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("good", sa.Integer(), nullable=False),
        sa.Column("satisfactory", sa.Integer(), nullable=False),
        sa.Column("moderate", sa.Integer(), nullable=False),
        sa.Column("poor", sa.Integer(), nullable=False),
        sa.Column("very_poor", sa.Integer(), nullable=False),
        sa.Column("severe", sa.Integer(), nullable=False),
        sa.Column("days_with_data", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_city_aqi_days_city_id_cities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
            name=op.f("fk_city_aqi_days_period_id_periods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("city_id", "period_id", name=op.f("pk_city_aqi_days")),
    )
    op.create_table(
        "city_dominant_days",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("pollutant", sa.String(length=8), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "pollutant IN ('PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3', 'NH3')",
            name=op.f("ck_city_dominant_days_pollutant"),
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_city_dominant_days_city_id_cities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
            name=op.f("fk_city_dominant_days_period_id_periods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "city_id", "period_id", "pollutant", name=op.f("pk_city_dominant_days")
        ),
    )
    op.create_table(
        "city_groups",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "code IN ('NCAP', 'MPC', 'IGP', 'DELHI_NCR', 'STATE_CAPITALS')",
            name=op.f("ck_city_groups_code"),
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_city_groups_city_id_cities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("city_id", "code", name=op.f("pk_city_groups")),
    )
    op.create_table(
        "city_pollutant_means",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("pollutant", sa.String(length=8), nullable=False),
        sa.Column("mean", sa.Float(), nullable=False),
        sa.Column("days_with_data", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "pollutant IN ('PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3', 'NH3')",
            name=op.f("ck_city_pollutant_means_pollutant"),
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_city_pollutant_means_city_id_cities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["periods.id"],
            name=op.f("fk_city_pollutant_means_period_id_periods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "city_id", "period_id", "pollutant", name=op.f("pk_city_pollutant_means")
        ),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name=op.f("fk_stations_city_id_cities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stations")),
        sa.UniqueConstraint("city_id", "name", name=op.f("uq_stations_city_id")),
    )
    op.create_table(
        "station_hourly",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pm25", sa.Float(), nullable=True),
        sa.Column("pm10", sa.Float(), nullable=True),
        sa.Column("no2", sa.Float(), nullable=True),
        sa.Column("so2", sa.Float(), nullable=True),
        sa.Column("co", sa.Float(), nullable=True),
        sa.Column("o3", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_station_hourly_station_id_stations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("station_id", "observed_at", name=op.f("pk_station_hourly")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("station_hourly")
    op.drop_table("stations")
    op.drop_table("city_pollutant_means")
    op.drop_table("city_groups")
    op.drop_table("city_dominant_days")
    op.drop_table("city_aqi_days")
    op.drop_table("periods")
    op.drop_table("datasets")
    op.drop_table("cities")
    # ### end Alembic commands ###
